language: android

jdk: oraclejdk8

sudo: false

env:
  global:
  - GRADLE_OPTS="-Xmx512m"

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-19
    - sys-img-armeabi-v7a-android-19
    - extra-google-m2repository
    - extra-android-m2repository

install:
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=tools
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=build-tools-25.0.3
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=android-19
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=sys-img-armeabi-v7a-android-19
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=extra-android-m2repository
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=extra-google-m2repository

script:
  - ./gradlew clean test

after_success:
  - ./gradlew jacoco coveralls
